# Generated by Django 5.0.6 on 2024-05-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('visited_times', models.IntegerField(default=1)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
