# Generated by Django 5.0.6 on 2024-05-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_brand_id_alter_cart_id_alter_color_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
