# Generated by Django 5.0.6 on 2024-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_tshirt_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ideal_for',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='neck_type',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='occassion',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sleeve_type',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
