# Generated by Django 5.0.6 on 2024-05-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_tshirt_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tshirt',
            new_name='product',
        ),
    ]
